#############################################################################
# Makefile for building: PGP
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  PGP.pro
# Template: app
# Command: /Applications/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile PGP.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -Wall -Wextra -pedantic -g -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I. -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Applications/Qt/5.4/clang_64/lib
QMAKE         = /Applications/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PGP1.0.0
DISTDIR = /Users/pavelcsoka/Google\ Drive/VUT\ MGM/PGP/projekt/PGP/.tmp/PGP1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Applications/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.4/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/ogl.cpp \
		src/texture3d.cpp \
		src/opengl_window.cpp \
		src/volume_window.cpp qrc_PGP_shaders.cpp \
		qrc_PGP_data.cpp \
		moc_opengl_window.cpp \
		moc_volume_window.cpp
OBJECTS       = main.o \
		ogl.o \
		texture3d.o \
		opengl_window.o \
		volume_window.o \
		qrc_PGP_shaders.o \
		qrc_PGP_data.o \
		moc_opengl_window.o \
		moc_volume_window.o
DIST          = /Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		PGP.pro src/ogl.h \
		src/texture3d.h \
		src/opengl_window.h \
		src/volume_window.h src/main.cpp \
		src/ogl.cpp \
		src/texture3d.cpp \
		src/opengl_window.cpp \
		src/volume_window.cpp
QMAKE_TARGET  = PGP
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = PGP

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PGP.pro /Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		PGP.pro \
		PGP_shaders.qrc \
		PGP_data.qrc \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile PGP.pro
/Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf:
PGP.pro:
PGP_shaders.qrc:
PGP_data.qrc:
/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile PGP.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents PGP_shaders.qrc PGP_data.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/ogl.h src/texture3d.h src/opengl_window.h src/volume_window.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/ogl.cpp src/texture3d.cpp src/opengl_window.cpp src/volume_window.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_PGP_shaders.cpp qrc_PGP_data.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_PGP_shaders.cpp qrc_PGP_data.cpp
qrc_PGP_shaders.cpp: PGP_shaders.qrc \
		src/opengl/volume_renderer.vert \
		src/opengl/volume_renderer.frag
	/Applications/Qt/5.4/clang_64/bin/rcc -name PGP_shaders PGP_shaders.qrc -o qrc_PGP_shaders.cpp

qrc_PGP_data.cpp: PGP_data.qrc \
		data/head256x256x109_8bit_chan.raw
	/Applications/Qt/5.4/clang_64/bin/rcc -name PGP_data PGP_data.qrc -o qrc_PGP_data.cpp

compiler_moc_header_make_all: moc_opengl_window.cpp moc_volume_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_opengl_window.cpp moc_volume_window.cpp
moc_opengl_window.cpp: src/opengl_window.h
	/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I'/Users/pavelcsoka/Google Drive/VUT MGM/PGP/projekt/PGP' -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.4/clang_64/lib src/opengl_window.h -o moc_opengl_window.cpp

moc_volume_window.cpp: src/opengl_window.h \
		src/texture3d.h \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLDebugLogger \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		src/volume_window.h
	/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I'/Users/pavelcsoka/Google Drive/VUT MGM/PGP/projekt/PGP' -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.4/clang_64/lib src/volume_window.h -o moc_volume_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/volume_window.h \
		src/opengl_window.h \
		src/texture3d.h \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLDebugLogger \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

ogl.o: src/ogl.cpp src/ogl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogl.o src/ogl.cpp

texture3d.o: src/texture3d.cpp src/texture3d.h \
		src/ogl.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texture3d.o src/texture3d.cpp

opengl_window.o: src/opengl_window.cpp src/opengl_window.h \
		src/ogl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opengl_window.o src/opengl_window.cpp

volume_window.o: src/volume_window.cpp src/volume_window.h \
		src/opengl_window.h \
		src/texture3d.h \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLDebugLogger \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		src/ogl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o volume_window.o src/volume_window.cpp

qrc_PGP_shaders.o: qrc_PGP_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_PGP_shaders.o qrc_PGP_shaders.cpp

qrc_PGP_data.o: qrc_PGP_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_PGP_data.o qrc_PGP_data.cpp

moc_opengl_window.o: moc_opengl_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_opengl_window.o moc_opengl_window.cpp

moc_volume_window.o: moc_volume_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_volume_window.o moc_volume_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

